apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: banking-app
spec:
  type: ClusterIP
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
