apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: banking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: ibraheemcisse/user-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: production
