apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: banking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: ibraheemcisse/account-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: USER_SERVICE_URL
          value: http://user-service:3001
