apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: banking-app
spec:
  type: ClusterIP
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
